import { Navbar } from "./_components/Navbar"

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function Layout({
    children,
}: {
    children: React.ReactNode
}) {
    console.log("Main Layout rendered");
    return (<>
        <Navbar />
        {children}
        </>
    )
}
